# Title

### Imports

In [20]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Load music.csv

In [2]:
music = pd.read_csv("music.csv")

### Top 10 Songs by Streams (Artist, Song) - In Descending and Ascending order

#### Song - Descending

In [16]:
music.groupby(["title"])['streams'].sum().sort_values(ascending=False).head(10).reset_index()

                                           title       streams
0                                   Shape of You  5.281159e+09
1                                Blinding Lights  5.262971e+09
2                                   Dance Monkey  4.682417e+09
3                              Someone You Loved  4.063598e+09
4  Sunflower - Spider-Man: Into the Spider-Verse  3.823160e+09
5                                       Señorita  3.636238e+09
6                                        bad guy  3.523698e+09
7                                Don't Start Now  3.298516e+09
8                                   Lucid Dreams  3.233953e+09
9                                        Happier  3.217228e+09

Text

#### Song - Ascending

In [17]:
# music.groupby(["title", "artist"])['streams'].sum().sort_values(ascending=True).head(10).reset_index()
music.groupby(["title"])['streams'].sum().sort_values(ascending=True).head(10).reset_index()

                                              title  streams
0                       La Guitarra - MTV Unplugged   1001.0
1  So Xclusive (feat. K-Slicc, Lo$Ta & Badazz Luck)   1001.0
2                                           ده و ده   1001.0
3                         Vesturbær (feat. Class B)   1002.0
4              Hvað Finnst Þér Um Það? (feat. Kilo)   1002.0
5                                               Eső   1002.0
6                               Homework As$ignment   1002.0
7                             Junkies Ate My Poodle   1002.0
8                                   Jäätunud Jäljed   1002.0
9                                            Divata   1002.0

Text

#### Artist - Descending

In [8]:
music.groupby("artist")['streams'].sum().sort_values(ascending=False).head(10).reset_index()

           artist       streams
0      Ed Sheeran  2.380505e+10
1     Post Malone  1.959290e+10
2           Drake  1.837706e+10
3   Billie Eilish  1.740249e+10
4   Ariana Grande  1.552421e+10
5        Dua Lipa  1.227534e+10
6      Juice WRLD  1.223138e+10
7      The Weeknd  1.222765e+10
8    XXXTENTACION  1.220035e+10
9  Olivia Rodrigo  9.644647e+09

Text

#### Artist - Ascending

In [9]:
music.groupby("artist")['streams'].sum().sort_values(ascending=True).head(10).reset_index()

                                     artist  streams
0            Street Pound Productions, Lota   1001.0
1                             Wegz, Abyusif   1001.0
2                                Ragga Holm   1002.0
3                                    Dossey   1002.0
4                               Mark Millar   1002.0
5                        RMT EN EL PRODUCTO   1003.0
6                              Trey Pearson   1003.0
7                               Bear Grillz   1004.0
8  Oliver Mtukudzi, Ladysmith Black Mambazo   1004.0
9              Joseph Trapanese, Joey Batey   1004.0

Text

### Top 10 Songs by Rank (Artist, Song) - In Descending and Ascending order

In [22]:
# sns.heatmap(music.corr(numeric_only=True), annot=True)
# plt.show()

### Correlation Analysis

### Covariance Analysis