In [4]:
import pandas as pd
music = pd.read_csv("charts.csv")

In [18]:
music.shape

(26173514, 9)

In [19]:
music[music['streams'] > 2000000]

,title,rank,date,artist,url,region,chart,trend,streams
3234,Starboy,1,2017-01-01,"The Weeknd, Daft Punk",https://open.spotify.com/track/5aAx2yezTd8zXrk...,Global,top200,SAME_POSITION,3135625.0
3235,Closer,2,2017-01-01,"The Chainsmokers, Halsey",https://open.spotify.com/track/7BKLCZ1jbUBVqRi...,Global,top200,SAME_POSITION,3015525.0
3236,Let Me Love You,3,2017-01-01,"DJ Snake, Justin Bieber",https://open.spotify.com/track/4pdPtRcBmOSQDlJ...,Global,top200,MOVE_UP,2545384.0
3237,Rockabye (feat. Sean Paul & Anne-Marie),4,2017-01-01,Clean Bandit,https://open.spotify.com/track/5knuzwU65gJK7IF...,Global,top200,MOVE_DOWN,2356604.0
3238,One Dance,5,2017-01-01,"Drake, WizKid, Kyla",https://open.spotify.com/track/1xznGGDReH1oQq0...,Global,top200,SAME_POSITION,2259887.0
...,...,...,...,...,...,...,...,...,...
25251443,Stir Fry,15,2018-01-31,Migos,https://open.spotify.com/track/2UVbBKQOdFAekPT...,Global,top200,SAME_POSITION,2224809.0
25251444,Sick Boy,16,2018-01-31,The Chainsmokers,https://open.spotify.com/track/7jqDzXJS0K0Re8u...,Global,top200,SAME_POSITION,2157006.0
25251445,"Let Me Go (with Alesso, Florida Georgia Line &...",17,2018-01-31,Hailee Steinfeld,https://open.spotify.com/track/5AEtlRudpgdT5Ft...,Global,top200,SAME_POSITION,2054277.0
25251446,I Fall Apart,18,2018-01-31,Post Malone,https://open.spotify.com/track/75ZvA4QfFiZvzhj...,Global,top200,SAME_POSITION,2034143.0
25275673,God's Plan,1,2018-01-31,Drake,https://open.spotify.com/track/2XW4DbS6NddZxRP...,United States,top200,SAME_POSITION,3805533.0

In [20]:
music.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26173514 entries, 0 to 26173513
Data columns (total 9 columns):
 #   Column   Dtype
---  ------   -----
 0   title    object
 1   rank     int64
 2   date     object
 3   artist   object
 4   url      object
 5   region   object
 6   chart    object
 7   trend    object
 8   streams  float64
dtypes: float64(1), int64(1), object(7)
memory usage: 1.8+ GB

In [21]:
# music.groupby('chart')['title'].value_counts()

In [22]:
music[music['title'] == 'Starboy']

,title,rank,date,artist,url,region,chart,trend,streams
28,Starboy,29,2017-01-01,"The Weeknd, Daft Punk",https://open.spotify.com/track/5aAx2yezTd8zXrk...,Argentina,top200,SAME_POSITION,65518.0
201,Starboy,1,2017-01-01,"The Weeknd, Daft Punk",https://open.spotify.com/track/5aAx2yezTd8zXrk...,Australia,top200,MOVE_UP,107350.0
408,Starboy,7,2017-01-01,"The Weeknd, Daft Punk",https://open.spotify.com/track/5aAx2yezTd8zXrk...,Austria,top200,MOVE_UP,9165.0
605,Starboy,3,2017-01-01,"The Weeknd, Daft Punk",https://open.spotify.com/track/5aAx2yezTd8zXrk...,Belgium,top200,MOVE_UP,17374.0
819,Starboy,17,2017-01-01,"The Weeknd, Daft Punk",https://open.spotify.com/track/5aAx2yezTd8zXrk...,Bolivia,top200,MOVE_DOWN,2480.0
...,...,...,...,...,...,...,...,...,...
25606434,Starboy,37,2021-02-11,"The Weeknd, Daft Punk",https://open.spotify.com/track/7MXVkk9YMctZqd1...,South Korea,viral50,MOVE_DOWN,NaN
25646367,Starboy,31,2021-02-12,"The Weeknd, Daft Punk",https://open.spotify.com/track/7MXVkk9YMctZqd1...,South Korea,viral50,MOVE_UP,NaN
25666554,Starboy,32,2021-02-13,"The Weeknd, Daft Punk",https://open.spotify.com/track/7MXVkk9YMctZqd1...,South Korea,viral50,MOVE_DOWN,NaN
25710113,Starboy,33,2021-02-14,"The Weeknd, Daft Punk",https://open.spotify.com/track/7MXVkk9YMctZqd1...,South Korea,viral50,MOVE_DOWN,NaN
26017226,Starboy,37,2021-02-28,"The Weeknd, Daft Punk",https://open.spotify.com/track/7MXVkk9YMctZqd1...,South Korea,viral50,NEW_ENTRY,NaN

In [23]:
# music.groupby('title').value_counts()

In [24]:
# music.head()

In [25]:
music.tail()

,title,rank,date,artist,url,region,chart,trend,streams
26173509,BYE,46,2021-07-31,Jaden,https://open.spotify.com/track/3OUyyDN7EZrL7i0...,Vietnam,viral50,MOVE_UP,NaN
26173510,Pillars,47,2021-07-31,My Anh,https://open.spotify.com/track/6eky30oFiQbHUAT...,Vietnam,viral50,NEW_ENTRY,NaN
26173511,Gái Độc Thân,48,2021-07-31,Tlinh,https://open.spotify.com/track/2klsSb2iTfgDh95...,Vietnam,viral50,MOVE_DOWN,NaN
26173512,Renegade (feat. Taylor Swift),49,2021-07-31,Big Red Machine,https://open.spotify.com/track/1aU1wpYBSpP0M6I...,Vietnam,viral50,MOVE_DOWN,NaN
26173513,Letter to Jarad,50,2021-07-31,"LRN Slime, Shiloh Dynasty",https://open.spotify.com/track/508QhA2SncMbh5C...,Vietnam,viral50,MOVE_DOWN,NaN

In [26]:
music.isnull().sum()

title           11
rank             0
date             0
artist          18
url              0
region           0
chart            0
trend            0
streams    5851610
dtype: int64

In [27]:
# subset.to_csv('subset.csv', index=False)

In [28]:
music['streams'].median()

np.float64(9565.0)

In [29]:
# music['price'] = music['streams'].fillna(music['streams'].median())
# music.isnull().sum()

In [31]:
music.loc[music['artist'].isnull()]

,title,rank,date,artist,url,region,chart,trend,streams
20596664,NO GOOD,10,2020-07-13,NaN,https://open.spotify.com/track/4Qnz8tARYhUtDNe...,Japan,viral50,NEW_ENTRY,NaN
20616457,NO GOOD,10,2020-07-14,NaN,https://open.spotify.com/track/4Qnz8tARYhUtDNe...,Japan,viral50,SAME_POSITION,NaN
20640094,NO GOOD,10,2020-07-15,NaN,https://open.spotify.com/track/4Qnz8tARYhUtDNe...,Japan,viral50,SAME_POSITION,NaN
20661724,NO GOOD,10,2020-07-16,NaN,https://open.spotify.com/track/4Qnz8tARYhUtDNe...,Japan,viral50,SAME_POSITION,NaN
20677645,NO GOOD,10,2020-07-17,NaN,https://open.spotify.com/track/4Qnz8tARYhUtDNe...,Japan,viral50,SAME_POSITION,NaN
20705363,NO GOOD,10,2020-07-18,NaN,https://open.spotify.com/track/4Qnz8tARYhUtDNe...,Japan,viral50,SAME_POSITION,NaN
20726697,NO GOOD,10,2020-07-19,NaN,https://open.spotify.com/track/4Qnz8tARYhUtDNe...,Japan,viral50,SAME_POSITION,NaN
20748638,NO GOOD,13,2020-07-20,NaN,https://open.spotify.com/track/4Qnz8tARYhUtDNe...,Japan,viral50,MOVE_DOWN,NaN
20788975,NO GOOD,14,2020-07-21,NaN,https://open.spotify.com/track/4Qnz8tARYhUtDNe...,Japan,viral50,MOVE_DOWN,NaN
20833982,NO GOOD,19,2020-07-22,NaN,https://open.spotify.com/track/4Qnz8tARYhUtDNe...,Japan,viral50,MOVE_DOWN,NaN
20865824,NO GOOD,23,2020-07-23,NaN,https://open.spotify.com/track/4Qnz8tARYhUtDNe...,Japan,viral50,MOVE_DOWN,NaN
20887012,NO GOOD,20,2020-07-24,NaN,https://open.spotify.com/track/4Qnz8tARYhUtDNe...,Japan,viral50,MOVE_UP,NaN
20903930,NO GOOD,21,2020-07-25,NaN,https://open.spotify.com/track/4Qnz8tARYhUtDNe...,Japan,viral50,MOVE_DOWN,NaN
20932541,NO GOOD,24,2020-07-26,NaN,https://open.spotify.com/track/4Qnz8tARYhUtDNe...,Japan,viral50,MOVE_DOWN,NaN
20960407,NO GOOD,36,2020-07-27,NaN,https://open.spotify.com/track/4Qnz8tARYhUtDNe...,Japan,viral50,MOVE_DOWN,NaN
20992837,NO GOOD,43,2020-07-28,NaN,https://open.spotify.com/track/4Qnz8tARYhUtDNe...,Japan,viral50,MOVE_DOWN,NaN
21026109,NO GOOD,40,2020-07-29,NaN,https://open.spotify.com/track/4Qnz8tARYhUtDNe...,Japan,viral50,MOVE_UP,NaN
21057585,NO GOOD,46,2020-07-30,NaN,https://open.spotify.com/track/4Qnz8tARYhUtDNe...,Japan,viral50,MOVE_DOWN,NaN

In [32]:
music.loc[music['title'].isnull()]

,title,rank,date,artist,url,region,chart,trend,streams
7305002,NaN,120,2019-06-24,Nissy,https://open.spotify.com/track/4cP6KmNvTFkLHZo...,Japan,top200,NEW_ENTRY,11942.0
7401555,NaN,167,2019-06-25,Nissy,https://open.spotify.com/track/4cP6KmNvTFkLHZo...,Japan,top200,MOVE_DOWN,10310.0
7479161,NaN,128,2019-06-26,Nissy,https://open.spotify.com/track/4cP6KmNvTFkLHZo...,Japan,top200,MOVE_UP,11620.0
7563494,NaN,164,2019-06-27,Nissy,https://open.spotify.com/track/4cP6KmNvTFkLHZo...,Japan,top200,MOVE_DOWN,10229.0
7670140,NaN,174,2019-06-28,Nissy,https://open.spotify.com/track/4cP6KmNvTFkLHZo...,Japan,top200,MOVE_DOWN,9348.0
7772268,NaN,188,2019-06-29,Nissy,https://open.spotify.com/track/4cP6KmNvTFkLHZo...,Japan,top200,MOVE_DOWN,9808.0
7879888,NaN,169,2019-06-30,Nissy,https://open.spotify.com/track/4cP6KmNvTFkLHZo...,Japan,top200,MOVE_UP,10900.0
14391788,NaN,38,2019-07-15,Nissy,https://open.spotify.com/track/4cP6KmNvTFkLHZo...,Japan,viral50,NEW_ENTRY,NaN
14481594,NaN,48,2019-07-16,Nissy,https://open.spotify.com/track/4cP6KmNvTFkLHZo...,Japan,viral50,MOVE_DOWN,NaN
14768101,NaN,46,2019-07-17,Nissy,https://open.spotify.com/track/4cP6KmNvTFkLHZo...,Japan,viral50,MOVE_UP,NaN
14773425,NaN,48,2019-07-18,Nissy,https://open.spotify.com/track/4cP6KmNvTFkLHZo...,Japan,viral50,MOVE_DOWN,NaN

In [11]:
music[(music['title'] == 'Hello') & (music['artist'] == 'Adele') & (music['region'] == 'Global')].sort_values(by='date')

,title,rank,date,artist,url,region,chart,trend,streams
3366,Hello,132,2017-01-01,Adele,https://open.spotify.com/track/4sPmO7WMQUAf45k...,Global,top200,MOVE_DOWN,448638.0
15442,Hello,123,2017-01-02,Adele,https://open.spotify.com/track/4sPmO7WMQUAf45k...,Global,top200,MOVE_UP,486853.0
39905,Hello,125,2017-01-03,Adele,https://open.spotify.com/track/4sPmO7WMQUAf45k...,Global,top200,MOVE_DOWN,523850.0
83699,Hello,127,2017-01-04,Adele,https://open.spotify.com/track/4sPmO7WMQUAf45k...,Global,top200,MOVE_DOWN,518782.0
143711,Hello,124,2017-01-05,Adele,https://open.spotify.com/track/4sPmO7WMQUAf45k...,Global,top200,MOVE_UP,529797.0
...,...,...,...,...,...,...,...,...,...
23388948,Hello,141,2021-10-19,Adele,https://open.spotify.com/track/1Yk0cQdMLx5RzzF...,Global,top200,MOVE_DOWN,860912.0
23469929,Hello,152,2021-10-20,Adele,https://open.spotify.com/track/1Yk0cQdMLx5RzzF...,Global,top200,MOVE_DOWN,833140.0
23444557,Hello,165,2021-10-21,Adele,https://open.spotify.com/track/1Yk0cQdMLx5RzzF...,Global,top200,MOVE_DOWN,810367.0
23590606,Hello,192,2021-10-22,Adele,https://open.spotify.com/track/1Yk0cQdMLx5RzzF...,Global,top200,MOVE_DOWN,807602.0
23831760,Hello,199,2021-10-25,Adele,https://open.spotify.com/track/1Yk0cQdMLx5RzzF...,Global,top200,NEW_ENTRY,719558.0

In [1]:
import pandas as pd
music_V2 = pd.read_csv("music.csv")

In [3]:
music_V2.shape

(26173485, 9)

In [13]:
music_V2['streams'].sum()

np.float64(1178985490738.0)

In [4]:
music_V2["artist"].nunique()

96156